/**
 * LLM Service
 * This module defines the LLMService class, which is responsible for interacting with the Ollama API to generate summaries of Twitch chat messages. It provides a method to summarize a list of chat messages and returns a concise summary that captures the main points of the conversation.
 */

import { config } from "../config";

export class LLMService {
  private ollamaUrl: string = config.ollama.apiUrl;

  /**
     * Summarizes a list of chat messages using the Ollama API.
     * @param messages An array of chat messages to summarize
     * @returns A summary string generated by the LLM
     */
  async summarize(messages: { username: string; message: string }[]): Promise<string> {
    const llamaRequestBody = {
      model: config.ollama.model,
      prompt: `Summarize the following Twitch chat messages in under 4 sentences, capturing the main topics discussed:\n\n${messages.map(m => `${m.username}: "${m.message}"`).join("\n")}`,
      stream: false
    }
    try {
      const response = await fetch(`${this.ollamaUrl}/api/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(llamaRequestBody)
      });

      if (!response.ok) {
        throw new Error(`Ollama API error: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();
      if (!data.response) {
        throw new Error("Ollama returned invalid response structure");
      }
      return data.response;
    } catch (error) {
      console.error("Error summarizing messages:", error);
      throw new Error("Failed to generate summary");
    }
  }
}