import { Router, Request, Response } from "express";
import { LLMService } from "../services/llmService";

const router = Router();

// POST /api/summarize
// Accepts an array of chat messages and returns a summary generated by the AI.
router.post("/", async (req: Request, res: Response) => {
  const { messages } = req.body;

  // Validate request body - must be an array
  if (!Array.isArray(messages) || messages.length === 0) {
    res.status(400).json({ error: "Missing or invalid 'messages' in request body" });
    return;
  }

  // Validate each message has username and message
  for (const msg of messages) {
    if (!msg.username || !msg.message) {
      res.status(400).json({ error: "Each message must have 'username' and 'message' fields" });
      return;
    }
  }

  try {
    // Call the AI summarization function (this is a placeholder)
    const summary = await summarizeChat(messages);
    res.json({ summary });
  } catch (err) {
    console.error("Error generating summary:", err);
    const errorMessage = err instanceof Error ? err.message : "Unknown error";
    res.status(500).json({
      error: "Failed to generate summary",
      details: errorMessage
    });
  }
});

const llmService = new LLMService();
// Function to call AI summarization method from LLMService
async function summarizeChat(messages: { username: string; message: string }[]): Promise<string> {
  return await llmService.summarize(messages);
}

export default router;